version: "3.8"

services:

  postgres:
    image: postgres:14
    container_name: dap_postgres
    environment:
      POSTGRES_DB: dap_db
      POSTGRES_USER: dap_user
      POSTGRES_PASSWORD: dap_pass
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  spark:
    image: bitnami/spark:latest
    container_name: dap_spark
    environment:
      - SPARK_MODE=master
    ports:
      - "7077:7077"
      - "8080:8080"
    volumes:
      - ./data:/data

  airflow:
    image: apache/airflow:2.8.1
    container_name: dap_airflow
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://dap_user:dap_pass@postgres:5432/dap_db
      AIRFLOW__CORE__FERNET_KEY: 'S18mWY3vY_tva8oRVRDEoXWhtbPK42kLly3_-esBcPM='
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
    volumes:
      - ./dags:/opt/airflow/dags
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    command: standalone 

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: dap_app
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    depends_on:
      - postgres

  data_loader:
    build:
      context: ./docker
      dockerfile: data_loader.Dockerfile
    container_name: dap_data_loader
    depends_on:
      - postgres
    volumes:
      - ./data:/data
      - ./docker/init_postgres:/init_postgres

volumes:
  pgdata:
